export const INCIDENTS = [
  {
    incidentId: "INC-2024-001",
    insuranceClaimNumber: "CLM-9943201",
    occurredAt: "2024-09-01T09:10:00",
    occurredDate: "2024-09-01",
    incidentKind: ["crash_report"],
    driver: {
      driverId: "DRV-2001",
      name: "John Smith",
      ageBand: "31 - 35",
      driverType: "Long Haul Driver",
      drivingExperience: "4 Years",
      lengthOfEmployment: "1 Year",
      hrsDriving: 4.5,
      hrsOnDuty: 6.0,
      email: "john.smith@example.com",
      phone: "(555) 000-0001",
      license: "SMI90228811",
      licenseState: "IL",
    },
    location: {
      unit: "",
      streetAddress: "6855 Columbus Rd",
      city: "Mississauga",
      stateOrProvince: "ON",
      country: "Canada",
      zip: "L5T 2G9",
      full: "Columbus Rd At 6855 Columbus Rd, Mississauga, ON L5T 2G9, Canada",
      geo: { lat: 43.599, lng: -79.652 },
      locationType: "Industrial Area",
    },
    vehicles: [
      {
        assetId: "TR-1049",
        vin: "1M8GDM9A6HP05X12",
        licenseNumber: "P-7762",
        licenseStateOrProvince: "Texas",
        vehicleType: "Power Unit",
        make: "Freightliner",
        model: "Cascadia",
        year: 2021,
        commodityType: "General Dry Freight",
        assetCategory: "CMV",
      },
      {
        assetId: "TR-2088",
        vin: "1A2B3C4D5E6F7G8H9",
        licenseNumber: "ABC-1234",
        licenseStateOrProvince: "Ontario",
        vehicleType: "Flatbed",
        make: "Kenworth",
        model: "T680",
        year: 2023,
        commodityType: "General Dry Freight",
        assetCategory: "CMV",
      },
      {
        assetId: "TR-4102",
        vin: "1GC4KYEY9KF192847",
        licenseNumber: "WRK-4422",
        licenseStateOrProvince: "Arizona",
        vehicleType: "Pickup",
        make: "Chevrolet",
        model: "Silverado 1500",
        year: 2019,
        commodityType: "",
        assetCategory: "Non-CMV",
      },
    ],
    severity: {
      fatalities: 0,
      injuriesNonFatal: 1,
      towAway: true,
      vehiclesTowed: 1,
      hazmatReleased: false,
      hazardousCommodity: "",
    },
    roadway: {
      postedSpeedLimitKmh: 60,
      roadType: "Urban",
      trafficControl: "Stop Sign",
      weatherConditions: "Clear",
      roadConditions: "Dry",
      light: "Daylight",
      terrain: "Straight and Flat",
    },
    classification: {
      fmcsaReportable: true,
      accidentType: "Tow Away",
      policeReport: true,
    },
    preventability: { value: "tbd", isPreventable: null, notes: "" },
    cause: {
      primaryCause: "Unsafe Behaviour",
      incidentType: "Rear-end collision",
    },
    costs: {
      currency: "USD",
      companyCostsFromDollarOne: 4500,
      insuranceCostsPaid: 12000,
      insuranceReserves: 8000,
      totalAccidentCosts: 24500,
    },
    followUp: {
      action: "Driver sent for remedial training on following distance.",
      comments: "Video evidence reviewed.",
    },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed", "ui_accident_table"],
    documents: [] as string[],
  },
  {
    incidentId: "INC-2024-002",
    insuranceClaimNumber: "CLM-8821034",
    occurredAt: "2024-08-15T14:30:00",
    occurredDate: "2024-08-15",
    incidentKind: ["operational_accident"],
    driver: {
      driverId: "DRV-2002",
      name: "Sarah Miller",
      ageBand: "31 - 35",
      driverType: "Local Driver",
      drivingExperience: "5 Years",
      lengthOfEmployment: "1 Year",
      hrsDriving: 2.0,
      hrsOnDuty: 3.5,
      email: "sarah.miller@example.com",
      phone: "(555) 000-0002",
      license: "MIL92003322",
      licenseState: "TX",
    },
    location: {
      unit: "",
      streetAddress: "I-35 Southbound Mile 214",
      city: "Dallas",
      stateOrProvince: "TX",
      country: "USA",
      zip: "75201",
      full: "I-35 Southbound Mile 214, Dallas, TX, USA",
      geo: { lat: 32.78, lng: -96.8 },
      locationType: "Urban Area",
    },
    vehicles: [
      {
        assetId: "TR-2088",
        vin: "1A2B3C4D5E6F7G8H9",
        licenseNumber: "ABC-1234",
        licenseStateOrProvince: "Ontario",
        vehicleType: "Power Unit",
        make: "Kenworth",
        model: "T680",
        year: 2023,
        commodityType: "Electronics",
      },
    ],
    severity: {
      fatalities: 0,
      injuriesNonFatal: 0,
      towAway: false,
      vehiclesTowed: 0,
      hazmatReleased: false,
      hazardousCommodity: "",
    },
    roadway: {
      postedSpeedLimitKmh: 100,
      roadType: "Interstate",
      trafficControl: "None",
      weatherConditions: "Rain",
      roadConditions: "Wet",
      light: "Daylight",
      terrain: "Curve Left",
    },
    classification: {
      fmcsaReportable: false,
      accidentType: "None",
      policeReport: false,
    },
    preventability: {
      value: "preventable",
      isPreventable: true,
      notes: "Driver failed to adjust speed for weather",
    },
    cause: {
      primaryCause: "Unsafe Behaviour",
      incidentType: "Single vehicle runoff",
    },
    costs: {
      currency: "USD",
      companyCostsFromDollarOne: 2200,
      insuranceCostsPaid: 0,
      insuranceReserves: 1500,
      totalAccidentCosts: 3700,
    },
    followUp: {
      action: "Verbal warning issued.",
      comments: "",
    },
    status: { value: "active", label: "Active" },
    sources: ["ui_accident_table"],
    documents: [],
  },
  {
    incidentId: "INC-2024-003",
    insuranceClaimNumber: "CLM-7765109",
    occurredAt: "2024-07-22T06:45:00",
    occurredDate: "2024-07-22",
    incidentKind: ["crash_report", "insurance_loss_event"],
    driver: {
      driverId: "DRV-1001",
      name: "James Sullivan",
      ageBand: "36 - 40",
      driverType: "Long Haul Driver",
      drivingExperience: "8 Years",
      lengthOfEmployment: "4 Years",
      hrsDriving: 8.0,
      hrsOnDuty: 9.0,
      email: "james.sullivan@example.com",
      phone: "(555) 123-4567",
      license: "SUL88291022",
      licenseState: "IL",
    },
    location: {
      unit: "",
      streetAddress: "Hwy 41 & Industrial Blvd",
      city: "Chicago",
      stateOrProvince: "IL",
      country: "USA",
      zip: "60601",
      full: "Hwy 41 & Industrial Blvd, Chicago, IL, USA",
      geo: { lat: 41.88, lng: -87.63 },
      locationType: "Industrial Area",
    },
    vehicles: [
      {
        assetId: "TR-3055",
        vin: "3GCP51C9XKG192837",
        licenseNumber: "HAUL-55",
        licenseStateOrProvince: "Nevada",
        vehicleType: "Power Unit",
        make: "Peterbilt",
        model: "389",
        year: 2020,
        commodityType: "Temperature Controlled",
      },
    ],
    severity: {
      fatalities: 1,
      injuriesNonFatal: 3,
      towAway: true,
      vehiclesTowed: 2,
      hazmatReleased: true,
      hazardousCommodity: "Diesel Fuel",
    },
    roadway: {
      postedSpeedLimitKmh: 80,
      roadType: "Highway",
      trafficControl: "Traffic Signal",
      weatherConditions: "Fog",
      roadConditions: "Wet",
      light: "Dawn",
      terrain: "Straight and Flat",
    },
    classification: {
      fmcsaReportable: true,
      accidentType: "Fatality",
      policeReport: true,
    },
    preventability: {
      value: "non_preventable",
      isPreventable: false,
      notes: "Other vehicle ran red light",
    },
    cause: {
      primaryCause: "Third Party",
      incidentType: "Intersection collision",
    },
    costs: {
      currency: "USD",
      companyCostsFromDollarOne: 35000,
      insuranceCostsPaid: 120000,
      insuranceReserves: 85000,
      totalAccidentCosts: 240000,
    },
    followUp: {
      action: "No action required - non-preventable.",
      comments: "Legal team handling.",
    },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed", "insurance_loss_register"],
    documents: [],
  },
  {
    incidentId: "INC-2024-004",
    insuranceClaimNumber: "CLM-3344556",
    occurredAt: "2024-06-10T19:20:00",
    occurredDate: "2024-06-10",
    incidentKind: ["insurance_loss_event"],
    driver: {
      driverId: "DRV-1003",
      name: "Robert Chen",
      ageBand: "31 - 35",
      driverType: "Owner Operator",
      drivingExperience: "8 Years",
      lengthOfEmployment: "4 Years",
      hrsDriving: 6.0,
      hrsOnDuty: 7.5,
      email: "r.chen@example.com",
      phone: "(555) 456-7890",
      license: "CHE99283321",
      licenseState: "CA",
    },
    location: {
      unit: "",
      streetAddress: "SR-528 Eastbound",
      city: "Orlando",
      stateOrProvince: "FL",
      country: "USA",
      zip: "32801",
      full: "SR-528 Eastbound, Orlando, FL, USA",
      geo: { lat: 28.43, lng: -81.31 },
      locationType: "Rural Area",
    },
    vehicles: [
      {
        assetId: "TR-6001",
        vin: "2FMZA5147XBA98765",
        licenseNumber: "TANK-01",
        licenseStateOrProvince: "Florida",
        vehicleType: "Power Unit",
        make: "Mack",
        model: "Granite",
        year: 2018,
        commodityType: "Auto Parts",
      },
    ],
    severity: {
      fatalities: 0,
      injuriesNonFatal: 0,
      towAway: true,
      vehiclesTowed: 1,
      hazmatReleased: false,
      hazardousCommodity: "",
    },
    roadway: {
      postedSpeedLimitKmh: 110,
      roadType: "Highway",
      trafficControl: "None",
      weatherConditions: "Clear",
      roadConditions: "Dry",
      light: "Dark - Lighted",
      terrain: "Straight and Flat",
    },
    classification: {
      fmcsaReportable: false,
      accidentType: "Tow Away",
      policeReport: false,
    },
    preventability: {
      value: "preventable",
      isPreventable: true,
      notes: "Tire blowout due to missed pre-trip inspection",
    },
    cause: {
      primaryCause: "Mechanical Failure",
      incidentType: "Tire blowout / rollover",
    },
    costs: {
      currency: "USD",
      companyCostsFromDollarOne: 8500,
      insuranceCostsPaid: 15000,
      insuranceReserves: 5000,
      totalAccidentCosts: 28500,
    },
    followUp: {
      action: "Maintenance review required.",
      comments: "",
    },
    status: { value: "active", label: "Active" },
    sources: ["insurance_loss_register"],
    documents: [],
  },
  {
    incidentId: "INC-2024-005",
    insuranceClaimNumber: "",
    occurredAt: "2024-05-03T11:00:00",
    occurredDate: "2024-05-03",
    incidentKind: ["operational_accident"],
    driver: {
      driverId: "DRV-2004",
      name: "Elena Rodriguez",
      ageBand: "26 - 30",
      driverType: "Driver Service/Lease",
      drivingExperience: "3 Years",
      lengthOfEmployment: "1 Year",
      hrsDriving: 1.0,
      hrsOnDuty: 2.0,
      email: "elena.rodriguez@example.com",
      phone: "(555) 000-0004",
      license: "ROD95221144",
      licenseState: "CA",
    },
    location: {
      unit: "Dock B",
      streetAddress: "400 Commerce Ave",
      city: "San Jose",
      stateOrProvince: "CA",
      country: "USA",
      zip: "95131",
      full: "Warehouse Dock B, 400 Commerce Ave, San Jose, CA, USA",
      geo: { lat: 37.34, lng: -121.89 },
      locationType: "Shipper",
    },
    vehicles: [
      {
        assetId: "TR-5200",
        vin: "5NPE24AF8FH123456",
        licenseNumber: "COLD-88",
        licenseStateOrProvince: "California",
        vehicleType: "Reefer",
        make: "Great Dane",
        model: "Everest",
        year: 2022,
        commodityType: "Dry Food Products",
      },
    ],
    severity: {
      fatalities: 0,
      injuriesNonFatal: 0,
      towAway: false,
      vehiclesTowed: 0,
      hazmatReleased: false,
      hazardousCommodity: "",
    },
    roadway: {
      postedSpeedLimitKmh: 15,
      roadType: "Private Property",
      trafficControl: "None",
      weatherConditions: "Clear",
      roadConditions: "Dry",
      light: "Daylight",
      terrain: "Straight and Flat",
    },
    classification: {
      fmcsaReportable: false,
      accidentType: "None",
      policeReport: false,
    },
    preventability: {
      value: "preventable",
      isPreventable: true,
      notes: "Backing without spotter",
    },
    cause: {
      primaryCause: "Unsafe Behaviour",
      incidentType: "Backing into structure",
    },
    costs: {
      currency: "USD",
      companyCostsFromDollarOne: 1800,
      insuranceCostsPaid: 0,
      insuranceReserves: 0,
      totalAccidentCosts: 1800,
    },
    followUp: {
      action: "Backing training assigned.",
      comments: "",
    },
    status: { value: "active", label: "Active" },
    sources: ["ui_accident_table"],
    documents: [],
  },
  {
    incidentId: "INC-2024-006",
    insuranceClaimNumber: "CLM-9988776",
    occurredAt: "2024-09-12T03:15:00",
    occurredDate: "2024-09-12",
    incidentKind: ["crash_report"],
    driver: {
      driverId: "DRV-1005",
      name: "Michael Brown",
      ageBand: "41 - 45",
      driverType: "Other",
      drivingExperience: "10 Years",
      lengthOfEmployment: "5 Years",
      hrsDriving: 3.5,
      hrsOnDuty: 4.0,
      email: "m.brown@example.com",
      phone: "(555) 777-8888",
      license: "BRO44556677",
      licenseState: "FL",
    },
    location: {
      unit: "",
      streetAddress: "I-71 Northbound MP 118",
      city: "Columbus",
      stateOrProvince: "OH",
      country: "USA",
      zip: "43215",
      full: "I-71 Northbound MP 118, Columbus, OH, USA",
      geo: { lat: 39.96, lng: -82.99 },
      locationType: "Urban Area",
    },
    vehicles: [
      {
        assetId: "TR-3055",
        vin: "3GCP51C9XKG192837",
        licenseNumber: "HAUL-55",
        licenseStateOrProvince: "Nevada",
        vehicleType: "Power Unit",
        make: "Peterbilt",
        model: "389",
        year: 2020,
        commodityType: "General Dry Freight",
      },
    ],
    severity: {
      fatalities: 0,
      injuriesNonFatal: 2,
      towAway: true,
      vehiclesTowed: 2,
      hazmatReleased: false,
      hazardousCommodity: "",
    },
    roadway: {
      postedSpeedLimitKmh: 105,
      roadType: "Interstate",
      trafficControl: "None",
      weatherConditions: "Clear",
      roadConditions: "Dry",
      light: "Dark - Not Lighted",
      terrain: "Curve Right",
    },
    classification: {
      fmcsaReportable: true,
      accidentType: "Injury",
      policeReport: true,
    },
    preventability: { value: "tbd", isPreventable: null, notes: "" },
    cause: {
      primaryCause: "Fatigue",
      incidentType: "Sideswipe - same direction",
    },
    costs: {
      currency: "USD",
      companyCostsFromDollarOne: 6200,
      insuranceCostsPaid: 18000,
      insuranceReserves: 12000,
      totalAccidentCosts: 36200,
    },
    followUp: {
      action: "Pending investigation.",
      comments: "Driver claims he was cut off.",
    },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed", "ui_accident_table"],
    documents: [],
  },
  {
    incidentId: "INC-2024-007",
    insuranceClaimNumber: "CLM-1112223",
    occurredAt: "2024-04-18T08:00:00",
    occurredDate: "2024-04-18",
    incidentKind: ["operational_accident", "insurance_loss_event"],
    driver: {
      driverId: "DRV-1002",
      name: "Maria Rodriguez",
      ageBand: "31 - 35",
      driverType: "Local Driver",
      drivingExperience: "5 Years",
      lengthOfEmployment: "2 Years",
      hrsDriving: 2.0,
      hrsOnDuty: 2.5,
      email: "m.rodriguez@example.com",
      phone: "(555) 987-6543",
      license: "ROD77382911",
      licenseState: "TX",
    },
    location: {
      unit: "",
      streetAddress: "I-85 Exit 246",
      city: "Atlanta",
      stateOrProvince: "GA",
      country: "USA",
      zip: "30303",
      full: "I-85 Exit 246, Atlanta, GA, USA",
      geo: { lat: 33.75, lng: -84.39 },
      locationType: "Urban Area",
    },
    vehicles: [
      {
        assetId: "TR-6001",
        vin: "2FMZA5147XBA98765",
        licenseNumber: "TANK-01",
        licenseStateOrProvince: "Florida",
        vehicleType: "Power Unit",
        make: "Mack",
        model: "Granite",
        year: 2018,
        commodityType: "General Flatbed Cargo",
      },
    ],
    severity: {
      fatalities: 0,
      injuriesNonFatal: 1,
      towAway: true,
      vehiclesTowed: 1,
      hazmatReleased: false,
      hazardousCommodity: "",
    },
    roadway: {
      postedSpeedLimitKmh: 90,
      roadType: "Interstate",
      trafficControl: "None",
      weatherConditions: "Rain",
      roadConditions: "Wet",
      light: "Daylight",
      terrain: "Downhill",
    },
    classification: {
      fmcsaReportable: true,
      accidentType: "Injury",
      policeReport: true,
    },
    preventability: {
      value: "preventable",
      isPreventable: true,
      notes: "Unsecured load shifted",
    },
    cause: {
      primaryCause: "Load Securement",
      incidentType: "Load shift / spill",
    },
    costs: {
      currency: "USD",
      companyCostsFromDollarOne: 11000,
      insuranceCostsPaid: 22000,
      insuranceReserves: 9000,
      totalAccidentCosts: 42000,
    },
    followUp: {
      action: "Securement retraining.",
      comments: "",
    },
    status: { value: "active", label: "Active" },
    sources: ["ui_accident_table", "insurance_loss_register"],
    documents: [],
  },
  {
    incidentId: "INC-2024-008",
    insuranceClaimNumber: "CLM-2234009",
    occurredAt: "2024-03-12T07:30:00",
    occurredDate: "2024-03-12",
    incidentKind: ["crash_report"],
    driver: { driverId: "DRV-1001", name: "James Sullivan", ageBand: "36 - 40", driverType: "Long Haul Driver", drivingExperience: "8 Years", lengthOfEmployment: "4 Years", hrsDriving: 7.0, hrsOnDuty: 8.5, email: "james.sullivan@example.com", phone: "(555) 123-4567", license: "SUL88291022", licenseState: "IL" },
    location: { unit: "", streetAddress: "I-80 Westbound MP 55", city: "Gary", stateOrProvince: "IN", country: "USA", zip: "46401", full: "I-80 Westbound MP 55, Gary, IN, USA", geo: { lat: 41.59, lng: -87.35 }, locationType: "Urban Area" },
    vehicles: [{ assetId: "TR-1049", vin: "1M8GDM9A6HP05X12", licenseNumber: "P-7762", licenseStateOrProvince: "Texas", vehicleType: "Power Unit", make: "Freightliner", model: "Cascadia", year: 2021, commodityType: "General Dry Freight", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 2, towAway: true, vehiclesTowed: 1, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 100, roadType: "Interstate", trafficControl: "None", weatherConditions: "Clear", roadConditions: "Dry", light: "Dawn", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: true, accidentType: "Injury", policeReport: true },
    preventability: { value: "preventable", isPreventable: true, notes: "Following too close" },
    cause: { primaryCause: "Unsafe Behaviour", incidentType: "Rear-end collision" },
    costs: { currency: "USD", companyCostsFromDollarOne: 5500, insuranceCostsPaid: 14000, insuranceReserves: 9000, totalAccidentCosts: 28500 },
    followUp: { action: "Following distance training assigned.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed"],
    documents: ["policeReport", "insuranceClaim", "medicalReport"],
  },
  {
    incidentId: "INC-2024-009",
    insuranceClaimNumber: "",
    occurredAt: "2024-02-28T15:45:00",
    occurredDate: "2024-02-28",
    incidentKind: ["operational_accident"],
    driver: { driverId: "DRV-1002", name: "Maria Rodriguez", ageBand: "31 - 35", driverType: "Local Driver", drivingExperience: "5 Years", lengthOfEmployment: "2 Years", hrsDriving: 3.0, hrsOnDuty: 4.0, email: "m.rodriguez@example.com", phone: "(555) 987-6543", license: "ROD77382911", licenseState: "TX" },
    location: { unit: "Bay 3", streetAddress: "9900 Distribution Way", city: "Houston", stateOrProvince: "TX", country: "USA", zip: "77032", full: "Bay 3, 9900 Distribution Way, Houston, TX, USA", geo: { lat: 29.97, lng: -95.34 }, locationType: "Shipper" },
    vehicles: [{ assetId: "TR-5200", vin: "5NPE24AF8FH123456", licenseNumber: "COLD-88", licenseStateOrProvince: "California", vehicleType: "Reefer", make: "Great Dane", model: "Everest", year: 2022, commodityType: "Temperature Controlled", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 0, towAway: false, vehiclesTowed: 0, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 15, roadType: "Private Property", trafficControl: "None", weatherConditions: "Clear", roadConditions: "Dry", light: "Daylight", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: false, accidentType: "None", policeReport: false },
    preventability: { value: "preventable", isPreventable: true, notes: "Dock collision - no spotter" },
    cause: { primaryCause: "Unsafe Behaviour", incidentType: "Backing into structure" },
    costs: { currency: "USD", companyCostsFromDollarOne: 2100, insuranceCostsPaid: 0, insuranceReserves: 0, totalAccidentCosts: 2100 },
    followUp: { action: "Backing safety refresher course.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["ui_accident_table"],
    documents: ["accidentPhoto"],
  },
  {
    incidentId: "INC-2024-010",
    insuranceClaimNumber: "CLM-5566778",
    occurredAt: "2024-01-15T22:10:00",
    occurredDate: "2024-01-15",
    incidentKind: ["crash_report", "insurance_loss_event"],
    driver: { driverId: "DRV-1003", name: "Robert Chen", ageBand: "31 - 35", driverType: "Owner Operator", drivingExperience: "8 Years", lengthOfEmployment: "4 Years", hrsDriving: 6.5, hrsOnDuty: 8.0, email: "r.chen@example.com", phone: "(555) 456-7890", license: "CHE99283321", licenseState: "CA" },
    location: { unit: "", streetAddress: "Hwy 101 Northbound MP 310", city: "San Francisco", stateOrProvince: "CA", country: "USA", zip: "94105", full: "Hwy 101 Northbound MP 310, San Francisco, CA, USA", geo: { lat: 37.77, lng: -122.42 }, locationType: "Urban Area" },
    vehicles: [{ assetId: "TR-3055", vin: "3GCP51C9XKG192837", licenseNumber: "HAUL-55", licenseStateOrProvince: "Nevada", vehicleType: "Straight Truck", make: "Peterbilt", model: "389", year: 2020, commodityType: "Electronics", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 1, towAway: true, vehiclesTowed: 2, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 90, roadType: "Highway", trafficControl: "None", weatherConditions: "Rain", roadConditions: "Wet", light: "Dark - Lighted", terrain: "Curve Left" },
    classification: { fmcsaReportable: true, accidentType: "Injury", policeReport: true },
    preventability: { value: "non_preventable", isPreventable: false, notes: "Other driver lost control" },
    cause: { primaryCause: "Third Party", incidentType: "Sideswipe - opposite direction" },
    costs: { currency: "USD", companyCostsFromDollarOne: 7200, insuranceCostsPaid: 21000, insuranceReserves: 14000, totalAccidentCosts: 42200 },
    followUp: { action: "Non-preventable - no action.", comments: "Legal team engaged." },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed", "insurance_loss_register"],
    documents: ["policeReport", "insuranceClaim", "medicalReport", "towReceipt", "accidentPhoto"],
  },
  {
    incidentId: "INC-2024-011",
    insuranceClaimNumber: "CLM-6677889",
    occurredAt: "2024-11-05T08:55:00",
    occurredDate: "2024-11-05",
    incidentKind: ["crash_report"],
    driver: { driverId: "DRV-2002", name: "Sarah Miller", ageBand: "31 - 35", driverType: "Local Driver", drivingExperience: "5 Years", lengthOfEmployment: "1 Year", hrsDriving: 2.5, hrsOnDuty: 3.5, email: "sarah.miller@example.com", phone: "(555) 000-0002", license: "MIL92003322", licenseState: "TX" },
    location: { unit: "", streetAddress: "US-290 Eastbound", city: "Austin", stateOrProvince: "TX", country: "USA", zip: "78701", full: "US-290 Eastbound, Austin, TX, USA", geo: { lat: 30.27, lng: -97.74 }, locationType: "Urban Area" },
    vehicles: [{ assetId: "TR-6001", vin: "2FMZA5147XBA98765", licenseNumber: "TANK-01", licenseStateOrProvince: "Florida", vehicleType: "Tanker", make: "Mack", model: "Granite", year: 2018, commodityType: "Auto Parts", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 0, towAway: true, vehiclesTowed: 1, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 80, roadType: "Urban", trafficControl: "Traffic Signal", weatherConditions: "Clear", roadConditions: "Dry", light: "Daylight", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: false, accidentType: "Tow Away", policeReport: true },
    preventability: { value: "tbd", isPreventable: null, notes: "" },
    cause: { primaryCause: "Unsafe Behaviour", incidentType: "Intersection collision" },
    costs: { currency: "USD", companyCostsFromDollarOne: 3800, insuranceCostsPaid: 9000, insuranceReserves: 5000, totalAccidentCosts: 17800 },
    followUp: { action: "Pending investigation.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed", "ui_accident_table"],
    documents: ["policeReport", "towReceipt"],
  },
  {
    incidentId: "INC-2024-012",
    insuranceClaimNumber: "",
    occurredAt: "2024-10-22T14:00:00",
    occurredDate: "2024-10-22",
    incidentKind: ["operational_accident"],
    driver: { driverId: "DRV-2004", name: "Elena Rodriguez", ageBand: "26 - 30", driverType: "Driver Service/Lease", drivingExperience: "3 Years", lengthOfEmployment: "1 Year", hrsDriving: 4.0, hrsOnDuty: 5.0, email: "elena.rodriguez@example.com", phone: "(555) 000-0004", license: "ROD95221144", licenseState: "CA" },
    location: { unit: "", streetAddress: "SR-99 Southbound MP 200", city: "Fresno", stateOrProvince: "CA", country: "USA", zip: "93720", full: "SR-99 Southbound MP 200, Fresno, CA, USA", geo: { lat: 36.74, lng: -119.77 }, locationType: "Highway" },
    vehicles: [{ assetId: "TR-2088", vin: "1A2B3C4D5E6F7G8H9", licenseNumber: "ABC-1234", licenseStateOrProvince: "Ontario", vehicleType: "Flatbed", make: "Kenworth", model: "T680", year: 2023, commodityType: "Dry Food Products", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 0, towAway: false, vehiclesTowed: 0, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 100, roadType: "Highway", trafficControl: "None", weatherConditions: "Fog", roadConditions: "Wet", light: "Dawn", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: false, accidentType: "None", policeReport: false },
    preventability: { value: "preventable", isPreventable: true, notes: "Failed to reduce speed in fog" },
    cause: { primaryCause: "Unsafe Behaviour", incidentType: "Single vehicle runoff" },
    costs: { currency: "USD", companyCostsFromDollarOne: 1500, insuranceCostsPaid: 0, insuranceReserves: 0, totalAccidentCosts: 1500 },
    followUp: { action: "Weather driving refresher.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["ui_accident_table"],
    documents: [],
  },
  {
    incidentId: "INC-2024-013",
    insuranceClaimNumber: "CLM-7788990",
    occurredAt: "2024-10-08T10:20:00",
    occurredDate: "2024-10-08",
    incidentKind: ["crash_report", "insurance_loss_event"],
    driver: { driverId: "DRV-1005", name: "Michael Brown", ageBand: "41 - 45", driverType: "Other", drivingExperience: "10 Years", lengthOfEmployment: "5 Years", hrsDriving: 5.0, hrsOnDuty: 6.0, email: "m.brown@example.com", phone: "(555) 777-8888", license: "BRO44556677", licenseState: "FL" },
    location: { unit: "", streetAddress: "I-10 Eastbound MP 412", city: "Phoenix", stateOrProvince: "AZ", country: "USA", zip: "85001", full: "I-10 Eastbound MP 412, Phoenix, AZ, USA", geo: { lat: 33.45, lng: -112.07 }, locationType: "Urban Area" },
    vehicles: [
      { assetId: "TR-1049", vin: "1M8GDM9A6HP05X12", licenseNumber: "P-7762", licenseStateOrProvince: "Texas", vehicleType: "Power Unit", make: "Freightliner", model: "Cascadia", year: 2021, commodityType: "Household Move", assetCategory: "CMV" },
      { assetId: "TR-4102", vin: "1GC4KYEY9KF192847", licenseNumber: "WRK-4422", licenseStateOrProvince: "Arizona", vehicleType: "Pickup", make: "Chevrolet", model: "Silverado 1500", year: 2019, commodityType: "", assetCategory: "Non-CMV" },
    ],
    severity: { fatalities: 0, injuriesNonFatal: 3, towAway: true, vehiclesTowed: 2, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 110, roadType: "Interstate", trafficControl: "None", weatherConditions: "Clear", roadConditions: "Dry", light: "Daylight", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: true, accidentType: "Injury", policeReport: true },
    preventability: { value: "non_preventable", isPreventable: false, notes: "Rear-ended at a stop" },
    cause: { primaryCause: "Third Party", incidentType: "Rear-end collision" },
    costs: { currency: "USD", companyCostsFromDollarOne: 12000, insuranceCostsPaid: 35000, insuranceReserves: 20000, totalAccidentCosts: 67000 },
    followUp: { action: "Non-preventable. Legal team handling.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed", "insurance_loss_register"],
    documents: ["policeReport", "insuranceClaim", "medicalReport", "accidentPhoto"],
  },
  {
    incidentId: "INC-2024-014",
    insuranceClaimNumber: "CLM-8899001",
    occurredAt: "2024-09-25T16:30:00",
    occurredDate: "2024-09-25",
    incidentKind: ["insurance_loss_event"],
    driver: { driverId: "DRV-2001", name: "John Smith", ageBand: "31 - 35", driverType: "Long Haul Driver", drivingExperience: "4 Years", lengthOfEmployment: "1 Year", hrsDriving: 9.0, hrsOnDuty: 10.5, email: "john.smith@example.com", phone: "(555) 000-0001", license: "SMI90228811", licenseState: "IL" },
    location: { unit: "", streetAddress: "I-70 Westbound MP 175", city: "Kansas City", stateOrProvince: "MO", country: "USA", zip: "64101", full: "I-70 Westbound MP 175, Kansas City, MO, USA", geo: { lat: 39.1, lng: -94.58 }, locationType: "Urban Area" },
    vehicles: [{ assetId: "TR-3055", vin: "3GCP51C9XKG192837", licenseNumber: "HAUL-55", licenseStateOrProvince: "Nevada", vehicleType: "Straight Truck", make: "Peterbilt", model: "389", year: 2020, commodityType: "General Dry Freight", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 0, towAway: true, vehiclesTowed: 1, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 105, roadType: "Interstate", trafficControl: "None", weatherConditions: "Clear", roadConditions: "Dry", light: "Dark - Not Lighted", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: false, accidentType: "Tow Away", policeReport: false },
    preventability: { value: "preventable", isPreventable: true, notes: "Tire blowout - missed inspection item" },
    cause: { primaryCause: "Mechanical Failure", incidentType: "Tire blowout" },
    costs: { currency: "USD", companyCostsFromDollarOne: 4200, insuranceCostsPaid: 8500, insuranceReserves: 3000, totalAccidentCosts: 15700 },
    followUp: { action: "Pre-trip inspection audit.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["insurance_loss_register"],
    documents: ["insuranceClaim", "towReceipt"],
  },
  {
    incidentId: "INC-2024-015",
    insuranceClaimNumber: "",
    occurredAt: "2024-08-30T06:15:00",
    occurredDate: "2024-08-30",
    incidentKind: ["operational_accident"],
    driver: { driverId: "DRV-1002", name: "Maria Rodriguez", ageBand: "31 - 35", driverType: "Local Driver", drivingExperience: "5 Years", lengthOfEmployment: "2 Years", hrsDriving: 1.5, hrsOnDuty: 2.0, email: "m.rodriguez@example.com", phone: "(555) 987-6543", license: "ROD77382911", licenseState: "TX" },
    location: { unit: "Loading Bay", streetAddress: "1200 Warehouse Blvd", city: "Memphis", stateOrProvince: "TN", country: "USA", zip: "38101", full: "Loading Bay, 1200 Warehouse Blvd, Memphis, TN, USA", geo: { lat: 35.15, lng: -90.05 }, locationType: "Receiver" },
    vehicles: [{ assetId: "TR-5200", vin: "5NPE24AF8FH123456", licenseNumber: "COLD-88", licenseStateOrProvince: "California", vehicleType: "Reefer", make: "Great Dane", model: "Everest", year: 2022, commodityType: "Dry Food Products", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 0, towAway: false, vehiclesTowed: 0, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 10, roadType: "Private Property", trafficControl: "None", weatherConditions: "Clear", roadConditions: "Dry", light: "Daylight", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: false, accidentType: "None", policeReport: false },
    preventability: { value: "preventable", isPreventable: true, notes: "Clipped dock corner" },
    cause: { primaryCause: "Unsafe Behaviour", incidentType: "Backing into structure" },
    costs: { currency: "USD", companyCostsFromDollarOne: 800, insuranceCostsPaid: 0, insuranceReserves: 0, totalAccidentCosts: 800 },
    followUp: { action: "Verbal warning.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["ui_accident_table"],
    documents: ["accidentPhoto"],
  },
  {
    incidentId: "INC-2024-016",
    insuranceClaimNumber: "CLM-9900112",
    occurredAt: "2024-07-04T13:45:00",
    occurredDate: "2024-07-04",
    incidentKind: ["crash_report"],
    driver: { driverId: "DRV-1003", name: "Robert Chen", ageBand: "31 - 35", driverType: "Owner Operator", drivingExperience: "8 Years", lengthOfEmployment: "4 Years", hrsDriving: 5.0, hrsOnDuty: 6.5, email: "r.chen@example.com", phone: "(555) 456-7890", license: "CHE99283321", licenseState: "CA" },
    location: { unit: "", streetAddress: "I-5 Northbound MP 88", city: "Sacramento", stateOrProvince: "CA", country: "USA", zip: "95814", full: "I-5 Northbound MP 88, Sacramento, CA, USA", geo: { lat: 38.58, lng: -121.49 }, locationType: "Urban Area" },
    vehicles: [{ assetId: "TR-6001", vin: "2FMZA5147XBA98765", licenseNumber: "TANK-01", licenseStateOrProvince: "Florida", vehicleType: "Tanker", make: "Mack", model: "Granite", year: 2018, commodityType: "General Flatbed Cargo", assetCategory: "CMV" }],
    severity: { fatalities: 1, injuriesNonFatal: 2, towAway: true, vehiclesTowed: 3, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 100, roadType: "Interstate", trafficControl: "None", weatherConditions: "Clear", roadConditions: "Dry", light: "Daylight", terrain: "Downhill" },
    classification: { fmcsaReportable: true, accidentType: "Fatality", policeReport: true },
    preventability: { value: "tbd", isPreventable: null, notes: "" },
    cause: { primaryCause: "Fatigue", incidentType: "Multi-vehicle chain collision" },
    costs: { currency: "USD", companyCostsFromDollarOne: 50000, insuranceCostsPaid: 180000, insuranceReserves: 120000, totalAccidentCosts: 350000 },
    followUp: { action: "Active investigation. Legal hold.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["fmcsa_crash_feed", "ui_accident_table"],
    documents: ["policeReport", "insuranceClaim", "medicalReport", "towReceipt"],
  },
  {
    incidentId: "INC-2024-017",
    insuranceClaimNumber: "",
    occurredAt: "2024-06-18T09:00:00",
    occurredDate: "2024-06-18",
    incidentKind: ["operational_accident"],
    driver: { driverId: "DRV-2004", name: "Elena Rodriguez", ageBand: "26 - 30", driverType: "Driver Service/Lease", drivingExperience: "3 Years", lengthOfEmployment: "1 Year", hrsDriving: 2.0, hrsOnDuty: 3.0, email: "elena.rodriguez@example.com", phone: "(555) 000-0004", license: "ROD95221144", licenseState: "CA" },
    location: { unit: "", streetAddress: "456 Logistics Park Dr", city: "Las Vegas", stateOrProvince: "NV", country: "USA", zip: "89101", full: "456 Logistics Park Dr, Las Vegas, NV, USA", geo: { lat: 36.17, lng: -115.14 }, locationType: "Industrial Area" },
    vehicles: [{ assetId: "TR-2088", vin: "1A2B3C4D5E6F7G8H9", licenseNumber: "ABC-1234", licenseStateOrProvince: "Ontario", vehicleType: "Flatbed", make: "Kenworth", model: "T680", year: 2023, commodityType: "General Flatbed Cargo", assetCategory: "CMV" }],
    severity: { fatalities: 0, injuriesNonFatal: 0, towAway: false, vehiclesTowed: 0, hazmatReleased: false, hazardousCommodity: "" },
    roadway: { postedSpeedLimitKmh: 25, roadType: "Private Property", trafficControl: "None", weatherConditions: "Clear", roadConditions: "Dry", light: "Daylight", terrain: "Straight and Flat" },
    classification: { fmcsaReportable: false, accidentType: "None", policeReport: false },
    preventability: { value: "preventable", isPreventable: true, notes: "Unsecured load shifted on turn" },
    cause: { primaryCause: "Load Securement", incidentType: "Load shift / spill" },
    costs: { currency: "USD", companyCostsFromDollarOne: 3200, insuranceCostsPaid: 0, insuranceReserves: 0, totalAccidentCosts: 3200 },
    followUp: { action: "Load securement audit initiated.", comments: "" },
    status: { value: "active", label: "Active" },
    sources: ["ui_accident_table"],
    documents: [],
  },
];
