import { MOCK_DRIVERS } from "@/data/mock-app-data";
import { VIOLATION_DATA } from "@/data/violations.data";
import type { Driver } from "@/data/mock-app-data";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ViolationRecord {
  id: string;
  date: string;            // ISO YYYY-MM-DD
  time: string;            // HH:mm (24-hr)
  driverId: string;
  driverName: string;
  driverType: string;
  driverExperience: string;
  assetId?: string;        // Linked vehicle ID
  assetName?: string;      // e.g. "TR-1049"
  locationState: string;
  locationCity?: string;
  locationStreet?: string;
  locationZip?: string;
  locationCountry?: string;
  location?: string;
  violationCode: string;
  violationDataId: string; // ID from VIOLATION_DATA (for full lookups)
  violationType: string;   // violationDescription from VIOLATION_DATA
  violationGroup: string;  // violationGroup from VIOLATION_DATA
  crashLikelihood: number; // from VIOLATION_DATA (capped at 100 for display)
  driverRiskCategory: number; // 1=High 2=Moderate 3=Lower
  isOos: boolean;
  result: 'Citation Issued' | 'Warning' | 'OOS Order' | 'Clean Inspection' | 'Under Review';
  // Money Fields
  fineAmount: number;
  expenseAmount: number;
  currency: 'USD' | 'CAD';
  // Deprecated: expenses (use expenseAmount instead or keep as alias)
  expenses: number;
  status: 'Open' | 'Closed' | 'Under Review';
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** All violation items flattened from every category in VIOLATION_DATA */
export const ALL_VIOLATIONS = Object.values(VIOLATION_DATA.categories).flatMap(c => c.items);

/** Look up a violation definition by its id */
export const getViolation = (id: string) => ALL_VIOLATIONS.find(v => v.id === id);

/** Calculate driving experience from hiredDate */
const calcExperience = (driver: Driver): string => {
  const pd = (driver as any);
  if (pd.drivingExperience) return pd.drivingExperience;
  const years = Math.floor((Date.now() - new Date(driver.hiredDate).getTime()) / (1000 * 60 * 60 * 24 * 365.25));
  return years <= 0 ? "< 1 Year" : `${years} Year${years === 1 ? "" : "s"}`;
};

// ─── Scenario Table ────────────────────────────────────────────────────────────
//
// Each row links a real driver (by name) to a real violation (by VIOLATION_DATA id).
// When you add a new driver to MOCK_DRIVERS, add rows here to assign violations to them.
// When Settings / Violations definitions change, crash risk & description update automatically.
//
// Columns: [recordId, date, time, driverName, violationDataId, state, result, $expenses, status]

type Scenario = [
  string,
  string,
  string,
  string,
  string,
  string,
  ViolationRecord['result'],
  number,
  ViolationRecord['status']
];

const SCENARIOS: Scenario[] = [
  // ── John Smith  |  Long Haul Driver  |  DRV-2001  |  Chicago, IL ──────────
  ["V-2025-001", "2025-01-08", "06:30", "John Smith",
    "392_5c2_violating_oos_order_alcohol",          "IL", "OOS Order",       0,   "Closed"],
  ["V-2024-002", "2024-05-20", "14:45", "John Smith",
    "392_4a_driver_uses_or_possesses_drugs",        "TX", "Citation Issued", 650, "Closed"],
  ["V-2024-001", "2024-03-12", "08:15", "John Smith",
    "392_5a_alcohol_4hrs_prior_to_duty",            "MO", "Citation Issued", 500, "Open"],

  // ── Sarah Miller  |  Local Driver  |  DRV-2002  |  Dallas, TX ───────────-
  ["V-2024-010", "2024-07-17", "09:20", "Sarah Miller",
    "392_5c2_violating_oos_order_alcohol",          "TX", "OOS Order",       0,   "Under Review"],
  ["V-2024-003", "2024-04-03", "11:00", "Sarah Miller",
    "392_5a3_intoxicating_beverage_on_duty",        "TX", "Warning",         0,   "Closed"],

  // ── Mike Johnson  |  Owner Operator  |  DRV-2003  |  Miami, FL ──────────-
  ["V-2025-002", "2025-02-05", "17:00", "Mike Johnson",
    "382_115_a_failing_to_implement_a_drugalcohol_testing", "GA", "Warning", 0, "Open"],
  ["V-2023-001", "2023-09-14", "22:30", "Mike Johnson",
    "392_4a_driver_uses_or_possesses_drugs",        "FL", "Citation Issued", 850, "Closed"],

  // ── Elena Rodriguez  |  Driver Service/Lease  |  DRV-2004  |  Sacramento, CA
  ["V-2024-011", "2024-11-30", "07:45", "Elena Rodriguez",
    "392_4a_driver_uses_or_possesses_drugs",        "NV", "Citation Issued", 500, "Closed"],
  ["V-2024-004", "2024-06-22", "13:10", "Elena Rodriguez",
    "392_5a_alcohol_4hrs_prior_to_duty",            "CA", "Warning",         0,   "Closed"],

  // ── James Sullivan  |  Long Haul Driver  |  DRV-1001  |  Springfield, IL ─
  ["V-2025-003", "2025-01-19", "15:35", "James Sullivan",
    "392_4a_driver_uses_or_possesses_drugs",        "OH", "Citation Issued", 750, "Open"],
  ["V-2024-005", "2024-02-14", "10:50", "James Sullivan",
    "392_5c2_violating_oos_order_alcohol",          "IN", "OOS Order",       0,   "Closed"],
  ["V-2023-002", "2023-12-01", "03:20", "James Sullivan",
    "392_5a3_intoxicating_beverage_on_duty",        "IL", "Citation Issued", 400, "Closed"],
];

// ─── Build Records from Scenarios ─────────────────────────────────────────────

const buildRecords = (): ViolationRecord[] => {
  const driverMap = new Map<string, Driver>(MOCK_DRIVERS.map(d => [d.name, d]));
  const records: ViolationRecord[] = [];

  for (const [id, date, time, driverName, violationId, state, result, expenses, status] of SCENARIOS) {
    const driver = driverMap.get(driverName);
    const v      = getViolation(violationId);

    // Skip if either the driver or the violation no longer exists in the system
    if (!driver || !v) continue;

    records.push({
      id,
      date,
      time,
      driverId:           driver.id,
      driverName:         driver.name,
      driverType:         driver.driverType || "Company Driver",
      driverExperience:   calcExperience(driver),
      locationState:      state,
      violationCode:      v.violationCode,
      violationDataId:    violationId,
      violationType:      v.violationDescription,
      violationGroup:     v.violationGroup,
      // Cap display at 100; values >100 in VIOLATION_DATA indicate extreme risk
      crashLikelihood:    Math.min(v.crashLikelihoodPercent ?? 0, 100),
      driverRiskCategory: v.driverRiskCategory,
      isOos:              v.isOos,
      result,
      // Map legacy "expenses" from scenario to fineAmount for now
      // Map legacy "expenses" from scenario to fineAmount for now
      fineAmount: expenses, 
      expenseAmount: 0,
      currency: 'USD',
      expenses, // Keep as legacy or total
      status,
      // Default mock address data
      locationCity: 'Unknown City',
      locationStreet: 'Mile Marker 100',
      locationZip: '00000',
      locationCountry: 'US',
    });
  }

  // ── Auto-Generate Random Records for Volume Testing ──
  const VIOLATION_DEFS = ALL_VIOLATIONS;
  const CITIES = [
      { c: "Phoenix", s: "AZ" }, { c: "Sacramento", s: "CA" }, { c: "Denver", s: "CO" }, 
      { c: "Miami", s: "FL" }, { c: "Atlanta", s: "GA" }, { c: "Chicago", s: "IL" },
      { c: "Indianapolis", s: "IN" }, { c: "Des Moines", s: "IA" }, { c: "Kansas City", s: "KS" },
      { c: "Louisville", s: "KY" }, { c: "New Orleans", s: "LA" }, { c: "Detroit", s: "MI" },
      { c: "Minneapolis", s: "MN" }, { c: "St. Louis", s: "MO" }, { c: "Las Vegas", s: "NV" },
      { c: "Albuquerque", s: "NM" }, { c: "Columbus", s: "OH" }, { c: "Oklahoma City", s: "OK" },
      { c: "Portland", s: "OR" }, { c: "Philadelphia", s: "PA" }, { c: "Nashville", s: "TN" },
      { c: "Houston", s: "TX" }, { c: "Salt Lake City", s: "UT" }, { c: "Seattle", s: "WA" }
  ];

  for (let i = 0; i < 40; i++) {
      const driver = MOCK_DRIVERS[i % MOCK_DRIVERS.length];
      const v = VIOLATION_DEFS[Math.floor(Math.random() * VIOLATION_DEFS.length)];
      const loc = CITIES[Math.floor(Math.random() * CITIES.length)];
      
      // Random date in last 2 years
      const dateObj = new Date();
      dateObj.setDate(dateObj.getDate() - Math.floor(Math.random() * 730));
      const dateStr = dateObj.toISOString().split('T')[0];
      
      const timeStr = `${Math.floor(Math.random() * 24).toString().padStart(2, '0')}:${Math.floor(Math.random() * 60).toString().padStart(2, '0')}`;
      
      const possibleResults: ViolationRecord['result'][] = ['Citation Issued', 'Warning', 'Clean Inspection', 'OOS Order'];
      const res = possibleResults[Math.floor(Math.random() * possibleResults.length)];
      
      const fine = res === 'Citation Issued' || res === 'OOS Order' ? Math.floor(Math.random() * 800) + 100 : 0;
      const status: ViolationRecord['status'] = Math.random() > 0.3 ? 'Closed' : 'Open';

      if (!driver || !v) continue;

      records.push({
          id: `V-AUTO-${1000 + i}`,
          date: dateStr,
          time: timeStr,
          driverId: driver.id,
          driverName: driver.name,
          driverType: driver.driverType || "Company Driver",
          driverExperience: calcExperience(driver),
          locationState: loc.s,
          locationCity: loc.c,
          locationStreet: `I-${Math.floor(Math.random() * 99) + 1} Mile Marker ${Math.floor(Math.random() * 300)}`,
          locationZip: Math.floor(10000 + Math.random() * 90000).toString(),
          locationCountry: 'US',
          violationCode: v.violationCode,
          violationDataId: v.id,
          violationType: v.violationDescription,
          violationGroup: v.violationGroup,
          crashLikelihood: Math.min(v.crashLikelihoodPercent ?? 0, 100),
          driverRiskCategory: v.driverRiskCategory, // Ensure this exists on v
          isOos: v.isOos,
          result: res,
          fineAmount: fine,
          expenseAmount: 0,
          currency: 'USD',
          expenses: fine,
          status,
      });
  }

  // Newest first
  return records.sort((a, b) => (a.date < b.date ? 1 : -1));
};



const INSP_RECORDS = [
  {
    "id": "VINSP-MIGRAHA00829-0",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3(a)1BOS",
    "violationDataId": "396_3_a_1bos_auto",
    "violationType": "Brake - Defective brakes >= 20% of service brakes on combo",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-1",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.47A-BSF",
    "violationDataId": "393_47a_bsf_auto",
    "violationType": "Brake malfunction causing smoke/fire from wheel end",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-2",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LCL",
    "violationDataId": "393_9a_lcl_auto",
    "violationType": "Lighting - Clearance lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-3",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LSML",
    "violationDataId": "393_9a_lsml_auto",
    "violationType": "Lighting - Side marker lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-4",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45B2-B",
    "violationDataId": "393_45b2_b_auto",
    "violationType": "Air Brake - Hose/tubing damaged or not secured",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-5",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45D-BAAL",
    "violationDataId": "393_45d_baal_auto",
    "violationType": "Air Brake - Audible air leak at other than a proper connection",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-6",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45B2-BHTD",
    "violationDataId": "393_45b2_bhtd_auto",
    "violationType": "Air Brake - Hose damage into the outer reinforcement ply",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-7",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.78A-WS",
    "violationDataId": "393_78a_ws_auto",
    "violationType": "Washers - Inoperative washing system",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-8",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSLRR",
    "violationDataId": "393_11a1_cslrr_auto",
    "violationType": "Lower rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-9",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-BALR",
    "violationDataId": "396_3a1_balr_auto",
    "violationType": "Air Brake - Fails air loss rate test",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-10",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-BALAC",
    "violationDataId": "396_3a1_balac_auto",
    "violationType": "Brake - Audible air leak from a brake chamber",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-11",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-ALBV",
    "violationDataId": "396_3a1_albv_auto",
    "violationType": "Air Brake - Any leak from a brake valve",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-12",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-ALATR",
    "violationDataId": "396_3a1_alatr_auto",
    "violationType": "Air Brake - Any leak from an air tank reservoir",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-13",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.5B-L",
    "violationDataId": "396_5b_l_auto",
    "violationType": "Lubrication - Oil or grease leak",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-14",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "395.24D-ELDPT",
    "violationDataId": "395_24d_eldpt_auto",
    "violationType": "Failure to produce and transfer ELD records on request",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-15",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.48A-BMBCBD",
    "violationDataId": "393_48a_bmbcbd_auto",
    "violationType": "Drum Brake - Missing/broken component(s)",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00829-16",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.47(e)",
    "violationDataId": "393_47e_clamp_roto_chamber_type_brake_s_out_of_adjustment",
    "violationType": "Clamp/Roto-Chamber type brake(s) out of adjustment",
    "violationGroup": "Brakes Out of Adjustment",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00829",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIHOULD04386-0",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LLPL",
    "violationDataId": "393_9a_llpl_auto",
    "violationType": "Lighting - License plate lamp inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIHOULD04386",
    "driverName": "SINGH KARANPREET",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA79568 (ON)"
  },
  {
    "id": "VINSP-MIHOULD04386-1",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSLRR",
    "violationDataId": "393_11a1_cslrr_auto",
    "violationType": "Lower rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIHOULD04386",
    "driverName": "SINGH KARANPREET",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA79568 (ON)"
  },
  {
    "id": "VINSP-MIHOULD04386-2",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LSLI",
    "violationDataId": "393_9a_lsli_auto",
    "violationType": "Lighting - Stop lamps inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIHOULD04386",
    "driverName": "SINGH KARANPREET",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA79568 (ON)"
  },
  {
    "id": "VINSP-MIHOULD04386-3",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LIL",
    "violationDataId": "393_9a_lil_auto",
    "violationType": "Lighting - Identification lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIHOULD04386",
    "driverName": "SINGH KARANPREET",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA79568 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-0",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSLRR",
    "violationDataId": "393_11a1_cslrr_auto",
    "violationType": "Lower rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-1",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LCL",
    "violationDataId": "393_9a_lcl_auto",
    "violationType": "Lighting - Clearance lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-2",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LRLI",
    "violationDataId": "393_9a_lrli_auto",
    "violationType": "Lighting - Tail lamp inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-3",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LHLI",
    "violationDataId": "393_9a_lhli_auto",
    "violationType": "Lighting - Headlamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-4",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "395.22H4",
    "violationDataId": "395_22h4_auto",
    "violationType": "ELD: Missing blank duty status graph-grids (min 8 days)",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-5",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "392.2-SLML",
    "violationDataId": "392_2_slml_auto",
    "violationType": "State/Local Laws - Failure to maintain lane",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-6",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-HLLH",
    "violationDataId": "393_9a_hllh_auto",
    "violationType": "Headlamp(s) fail to operate on low and high beam",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-7",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45B2-B",
    "violationDataId": "393_45b2_b_auto",
    "violationType": "Air Brake - Hose/tubing damaged or not secured",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00796-8",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSURR",
    "violationDataId": "393_11a1_csurr_auto",
    "violationType": "Upper rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00796",
    "driverName": "S. MUTHUKUMARASOORIYAR",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA53989 (ON)"
  },
  {
    "id": "VINSP-MICOPEK02873-0",
    "date": "2024-10-08",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LRLI",
    "violationDataId": "393_9a_lrli_auto",
    "violationType": "Lighting - Tail lamp inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MICOPEK02873",
    "driverName": "SINGH KARANPREET",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA79568 (ON)"
  },
  {
    "id": "VINSP-MICOPEK02873-1",
    "date": "2024-10-08",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.75C",
    "violationDataId": "393_75c_auto",
    "violationType": "Tires - Less than 2/32 inch tread depth",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MICOPEK02873",
    "driverName": "SINGH KARANPREET",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA79568 (ON)"
  },
  {
    "id": "VINSP-MICOPEK02873-2",
    "date": "2024-10-08",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.95A1",
    "violationDataId": "393_95a1_auto",
    "violationType": "Fire Extinguisher missing or not properly rated",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MICOPEK02873",
    "driverName": "SINGH KARANPREET",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA79568 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-0",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.209(d)",
    "violationDataId": "393_209d_steering_system_components_worn_welded_missing",
    "violationType": "Steering system components worn/welded/missing",
    "violationGroup": "Steering Mechanism",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-1",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.53(b)",
    "violationDataId": "393_53b_automatic_brake_adjuster_cmv_manufactured_on_or_after_10_20_1994_air_brake",
    "violationType": "Automatic brake adjuster CMV manufactured on or after 10/20/1994 – air brake",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-2",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45(b)(2)",
    "violationDataId": "393_45b2_failing_to_secure_brake_hose_tubing_against_mechanical_damage",
    "violationType": "Failing to secure brake hose/tubing against mechanical damage",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-3",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.5(b)",
    "violationDataId": "396_5b_oil_and_or_grease_leak",
    "violationType": "Oil and/or grease leak",
    "violationGroup": "Other Vehicle Defect",
    "crashLikelihood": 18,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-4",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.48(a)",
    "violationDataId": "393_48a_inoperative_defective_brakes",
    "violationType": "Inoperative/defective brakes",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-5",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9(a)",
    "violationDataId": "393_9a_inoperative_required_lamps",
    "violationType": "Inoperative required lamps",
    "violationGroup": "Clearance Identification Lamps/Other",
    "crashLikelihood": 18,
    "driverRiskCategory": 3,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-6",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45DLUV",
    "violationDataId": "393_45dluv_brake_connections_with_leaks_under_vehicle",
    "violationType": "Brake Connections with Leaks Under Vehicle",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-7",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.48A-BMBC",
    "violationDataId": "393_48a_bmbc_brakes_missing_or_broken_components",
    "violationType": "Brakes – Missing or Broken Components",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  },
  {
    "id": "VINSP-MIGRAHA00524-8",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.47(e)",
    "violationDataId": "393_47e_clamp_roto_chamber_type_brake_s_out_of_adjustment",
    "violationType": "Clamp/Roto-Chamber type brake(s) out of adjustment",
    "violationGroup": "Brakes Out of Adjustment",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "driverId": "DRV-INSP-MIGRAHA00524",
    "driverName": "RAJ HANS",
    "driverType": "Company Driver",
    "driverExperience": "5 Years",
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US",
    "assetName": "PA15366 (ON)"
  }
];
export const MOCK_VIOLATION_RECORDS: ViolationRecord[] = [...buildRecords(), ...INSP_RECORDS as any];


export interface AssetViolationRecord extends ViolationRecord {
  assetId: string;
  assetUnitNumber: string;
  assetMakeModel: string;
  assetPlate: string;
  assetType: string;
  linkedDriverId?: string;
  linkedDriverName?: string;
  crashLikelihoodPercent?: number; 
}
const INSP_ASSET_RECORDS = [
  {
    "id": "AVINSP-MIGRAHA00829-0",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3(a)1BOS",
    "violationDataId": "396_3_a_1bos_auto",
    "violationType": "Brake - Defective brakes >= 20% of service brakes on combo",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-1",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.47A-BSF",
    "violationDataId": "393_47a_bsf_auto",
    "violationType": "Brake malfunction causing smoke/fire from wheel end",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-2",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LCL",
    "violationDataId": "393_9a_lcl_auto",
    "violationType": "Lighting - Clearance lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 15,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-3",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LSML",
    "violationDataId": "393_9a_lsml_auto",
    "violationType": "Lighting - Side marker lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 15,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-4",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45B2-B",
    "violationDataId": "393_45b2_b_auto",
    "violationType": "Air Brake - Hose/tubing damaged or not secured",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-5",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45D-BAAL",
    "violationDataId": "393_45d_baal_auto",
    "violationType": "Air Brake - Audible air leak at other than a proper connection",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-6",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45B2-BHTD",
    "violationDataId": "393_45b2_bhtd_auto",
    "violationType": "Air Brake - Hose damage into the outer reinforcement ply",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-7",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.78A-WS",
    "violationDataId": "393_78a_ws_auto",
    "violationType": "Washers - Inoperative washing system",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 15,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-8",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSLRR",
    "violationDataId": "393_11a1_cslrr_auto",
    "violationType": "Lower rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-9",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-BALR",
    "violationDataId": "396_3a1_balr_auto",
    "violationType": "Air Brake - Fails air loss rate test",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-10",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-BALAC",
    "violationDataId": "396_3a1_balac_auto",
    "violationType": "Brake - Audible air leak from a brake chamber",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-11",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-ALBV",
    "violationDataId": "396_3a1_albv_auto",
    "violationType": "Air Brake - Any leak from a brake valve",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-12",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.3A1-ALATR",
    "violationDataId": "396_3a1_alatr_auto",
    "violationType": "Air Brake - Any leak from an air tank reservoir",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-13",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.5B-L",
    "violationDataId": "396_5b_l_auto",
    "violationType": "Lubrication - Oil or grease leak",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-15",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.48A-BMBCBD",
    "violationDataId": "393_48a_bmbcbd_auto",
    "violationType": "Drum Brake - Missing/broken component(s)",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00829-16",
    "date": "2025-02-06",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.47(e)",
    "violationDataId": "393_47e_clamp_roto_chamber_type_brake_s_out_of_adjustment",
    "violationType": "Clamp/Roto-Chamber type brake(s) out of adjustment",
    "violationGroup": "Brakes Out of Adjustment",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00829",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00829",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIHOULD04386-0",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LLPL",
    "violationDataId": "393_9a_llpl_auto",
    "violationType": "Lighting - License plate lamp inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIHOULD04386",
    "assetName": "PA79568 (ON)",
    "assetUnitNumber": "PA79568 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA79568 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIHOULD04386",
    "linkedDriverName": "SINGH KARANPREET",
    "crashLikelihoodPercent": 15,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIHOULD04386-1",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSLRR",
    "violationDataId": "393_11a1_cslrr_auto",
    "violationType": "Lower rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIHOULD04386",
    "assetName": "PA79568 (ON)",
    "assetUnitNumber": "PA79568 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA79568 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIHOULD04386",
    "linkedDriverName": "SINGH KARANPREET",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIHOULD04386-2",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LSLI",
    "violationDataId": "393_9a_lsli_auto",
    "violationType": "Lighting - Stop lamps inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIHOULD04386",
    "assetName": "PA79568 (ON)",
    "assetUnitNumber": "PA79568 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA79568 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIHOULD04386",
    "linkedDriverName": "SINGH KARANPREET",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIHOULD04386-3",
    "date": "2025-01-07",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LIL",
    "violationDataId": "393_9a_lil_auto",
    "violationType": "Lighting - Identification lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIHOULD04386",
    "assetName": "PA79568 (ON)",
    "assetUnitNumber": "PA79568 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA79568 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIHOULD04386",
    "linkedDriverName": "SINGH KARANPREET",
    "crashLikelihoodPercent": 15,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00796-0",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSLRR",
    "violationDataId": "393_11a1_cslrr_auto",
    "violationType": "Lower rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00796",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00796",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00796-1",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LCL",
    "violationDataId": "393_9a_lcl_auto",
    "violationType": "Lighting - Clearance lamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00796",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00796",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 15,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00796-2",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LRLI",
    "violationDataId": "393_9a_lrli_auto",
    "violationType": "Lighting - Tail lamp inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00796",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00796",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00796-3",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LHLI",
    "violationDataId": "393_9a_lhli_auto",
    "violationType": "Lighting - Headlamp(s) inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00796",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00796",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00796-6",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-HLLH",
    "violationDataId": "393_9a_hllh_auto",
    "violationType": "Headlamp(s) fail to operate on low and high beam",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00796",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00796",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00796-7",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45B2-B",
    "violationDataId": "393_45b2_b_auto",
    "violationType": "Air Brake - Hose/tubing damaged or not secured",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00796",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00796",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00796-8",
    "date": "2024-12-26",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.11A1-CSURR",
    "violationDataId": "393_11a1_csurr_auto",
    "violationType": "Upper rear retro-reflective sheeting missing",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 45,
    "driverRiskCategory": 2,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00796",
    "assetName": "PA53989 (ON)",
    "assetUnitNumber": "PA53989 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA53989 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00796",
    "linkedDriverName": "S. MUTHUKUMARASOORIYAR",
    "crashLikelihoodPercent": 45,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MICOPEK02873-0",
    "date": "2024-10-08",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9A-LRLI",
    "violationDataId": "393_9a_lrli_auto",
    "violationType": "Lighting - Tail lamp inoperative",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MICOPEK02873",
    "assetName": "PA79568 (ON)",
    "assetUnitNumber": "PA79568 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA79568 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MICOPEK02873",
    "linkedDriverName": "SINGH KARANPREET",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MICOPEK02873-1",
    "date": "2024-10-08",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.75C",
    "violationDataId": "393_75c_auto",
    "violationType": "Tires - Less than 2/32 inch tread depth",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 85,
    "driverRiskCategory": 1,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MICOPEK02873",
    "assetName": "PA79568 (ON)",
    "assetUnitNumber": "PA79568 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA79568 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MICOPEK02873",
    "linkedDriverName": "SINGH KARANPREET",
    "crashLikelihoodPercent": 85,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MICOPEK02873-2",
    "date": "2024-10-08",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.95A1",
    "violationDataId": "393_95a1_auto",
    "violationType": "Fire Extinguisher missing or not properly rated",
    "violationGroup": "Misc (Auto Added)",
    "crashLikelihood": 15,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MICOPEK02873",
    "assetName": "PA79568 (ON)",
    "assetUnitNumber": "PA79568 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA79568 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MICOPEK02873",
    "linkedDriverName": "SINGH KARANPREET",
    "crashLikelihoodPercent": 15,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-0",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.209(d)",
    "violationDataId": "393_209d_steering_system_components_worn_welded_missing",
    "violationType": "Steering system components worn/welded/missing",
    "violationGroup": "Steering Mechanism",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-1",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.53(b)",
    "violationDataId": "393_53b_automatic_brake_adjuster_cmv_manufactured_on_or_after_10_20_1994_air_brake",
    "violationType": "Automatic brake adjuster CMV manufactured on or after 10/20/1994 – air brake",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-2",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45(b)(2)",
    "violationDataId": "393_45b2_failing_to_secure_brake_hose_tubing_against_mechanical_damage",
    "violationType": "Failing to secure brake hose/tubing against mechanical damage",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-3",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "396.5(b)",
    "violationDataId": "396_5b_oil_and_or_grease_leak",
    "violationType": "Oil and/or grease leak",
    "violationGroup": "Other Vehicle Defect",
    "crashLikelihood": 18,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 18,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-4",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.48(a)",
    "violationDataId": "393_48a_inoperative_defective_brakes",
    "violationType": "Inoperative/defective brakes",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-5",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.9(a)",
    "violationDataId": "393_9a_inoperative_required_lamps",
    "violationType": "Inoperative required lamps",
    "violationGroup": "Clearance Identification Lamps/Other",
    "crashLikelihood": 18,
    "driverRiskCategory": 3,
    "isOos": true,
    "result": "OOS Order",
    "fineAmount": 500,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 500,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 18,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-6",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.45DLUV",
    "violationDataId": "393_45dluv_brake_connections_with_leaks_under_vehicle",
    "violationType": "Brake Connections with Leaks Under Vehicle",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-7",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.48A-BMBC",
    "violationDataId": "393_48a_bmbc_brakes_missing_or_broken_components",
    "violationType": "Brakes – Missing or Broken Components",
    "violationGroup": "Brakes, All Others",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  },
  {
    "id": "AVINSP-MIGRAHA00524-8",
    "date": "2024-04-10",
    "time": "12:00",
    "locationState": "MI",
    "violationCode": "393.47(e)",
    "violationDataId": "393_47e_clamp_roto_chamber_type_brake_s_out_of_adjustment",
    "violationType": "Clamp/Roto-Chamber type brake(s) out of adjustment",
    "violationGroup": "Brakes Out of Adjustment",
    "crashLikelihood": 29,
    "driverRiskCategory": 3,
    "isOos": false,
    "result": "Citation Issued",
    "fineAmount": 200,
    "expenseAmount": 0,
    "currency": "USD",
    "expenses": 200,
    "status": "Closed",
    "assetId": "AST-MIGRAHA00524",
    "assetName": "PA15366 (ON)",
    "assetUnitNumber": "PA15366 (ON)",
    "assetMakeModel": "TRUCK TRACTOR",
    "assetPlate": "PA15366 (ON)",
    "assetType": "TRUCK TRACTOR",
    "linkedDriverId": "DRV-INSP-MIGRAHA00524",
    "linkedDriverName": "RAJ HANS",
    "crashLikelihoodPercent": 29,
    "locationCity": "Unknown City",
    "locationStreet": "Inspection Station",
    "locationZip": "00000",
    "locationCountry": "US"
  }
];
export const MOCK_ASSET_VIOLATION_RECORDS: AssetViolationRecord[] = [...INSP_ASSET_RECORDS as any];