// Company branding shared across every form generated by the ATS.
//
// Persisted to localStorage so the admin's customisations survive a reload.
// Returns the branding object + a setter via the `useCompanyBranding` hook so
// every consumer (admin BrandingPanel · PDF generator · applicant preview)
// stays in sync.

import { useCallback, useEffect, useState } from "react";

export interface CompanyBranding {
    name: string;
    /** Optional one-line tagline shown under the company name. */
    tagline?: string;
    /** Mailing / physical address printed on the form footer. */
    address?: string;
    phone?: string;
    email?: string;
    /** Hex colour string used as the PDF accent (header bar). */
    accentColor: string;
    /** Logo data URL — PNG or SVG. Stored in localStorage. */
    logoDataUrl?: string;
}

const STORAGE_KEY = 'ats_company_branding_v1';

const DEFAULT_BRANDING: CompanyBranding = {
    name: 'Acme Trucking Inc.',
    tagline: 'Safety. Compliance. Driven.',
    address: '1240 Logistics Way · Aberdeen, MD 21001',
    phone: '(410) 555-0117',
    email: 'hr@acmetrucking.com',
    accentColor: '#2563eb',
};

function readFromStorage(): CompanyBranding {
    if (typeof window === 'undefined') return DEFAULT_BRANDING;
    try {
        const raw = window.localStorage.getItem(STORAGE_KEY);
        if (!raw) return DEFAULT_BRANDING;
        const parsed = JSON.parse(raw) as CompanyBranding;
        // Merge so missing keys fall back to defaults.
        return { ...DEFAULT_BRANDING, ...parsed };
    } catch {
        return DEFAULT_BRANDING;
    }
}

function writeToStorage(branding: CompanyBranding) {
    if (typeof window === 'undefined') return;
    try {
        window.localStorage.setItem(STORAGE_KEY, JSON.stringify(branding));
        // Notify other hook instances in the same tab.
        window.dispatchEvent(new CustomEvent('ats-branding-updated'));
    } catch { /* ignore quota errors */ }
}

export function useCompanyBranding(): [CompanyBranding, (next: Partial<CompanyBranding>) => void] {
    const [branding, setBranding] = useState<CompanyBranding>(() => readFromStorage());

    useEffect(() => {
        const onUpdate = () => setBranding(readFromStorage());
        window.addEventListener('ats-branding-updated', onUpdate);
        window.addEventListener('storage', (e) => { if (e.key === STORAGE_KEY) onUpdate(); });
        return () => {
            window.removeEventListener('ats-branding-updated', onUpdate);
        };
    }, []);

    const update = useCallback((patch: Partial<CompanyBranding>) => {
        setBranding(prev => {
            const next = { ...prev, ...patch };
            writeToStorage(next);
            return next;
        });
    }, []);

    return [branding, update];
}

export function readCompanyBranding(): CompanyBranding {
    return readFromStorage();
}
