// Accounts / Carriers — Frontend Mock Database
// Single source of truth for the Accounts list view and, eventually,
// per-carrier profile routing. Keep shape stable; pages import from here.

export type AccountStatus = 'Active' | 'Inactive' | 'Suspended' | 'Pending';
export type SafetyRating = 'Satisfactory' | 'Conditional' | 'Unsatisfactory' | 'Not Rated';
export type AccountCountry = 'US' | 'CA';

export interface AccountRecord {
    id: string;
    legalName: string;
    dbaName: string;
    dotNumber: string;
    mcNumber: string;
    status: AccountStatus;
    city: string;
    state: string;
    country: AccountCountry;
    drivers: number;
    assets: number;
    safetyRating: SafetyRating;
    createdAt: string;
    profilePath: string;
}

export const ACCOUNTS_DB: AccountRecord[] = [
    {
        id: 'acct-001',
        legalName: 'Acme Trucking Inc.',
        dbaName: 'Acme Logistics',
        dotNumber: '1234567',
        mcNumber: 'MC-876543',
        status: 'Active',
        city: 'Wilmington',
        state: 'DE',
        country: 'US',
        drivers: 148,
        assets: 92,
        safetyRating: 'Satisfactory',
        createdAt: '2019-01-15',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-002',
        legalName: 'Cascade Freight Systems LLC',
        dbaName: 'Cascade Freight',
        dotNumber: '2891034',
        mcNumber: 'MC-521098',
        status: 'Active',
        city: 'Portland',
        state: 'OR',
        country: 'US',
        drivers: 86,
        assets: 54,
        safetyRating: 'Satisfactory',
        createdAt: '2020-06-04',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-003',
        legalName: 'Northern Lights Transport Ltd.',
        dbaName: 'NL Transport',
        dotNumber: '—',
        mcNumber: '—',
        status: 'Active',
        city: 'Mississauga',
        state: 'ON',
        country: 'CA',
        drivers: 212,
        assets: 138,
        safetyRating: 'Satisfactory',
        createdAt: '2017-09-22',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-004',
        legalName: 'Sunbelt Haulers Corporation',
        dbaName: 'Sunbelt Haulers',
        dotNumber: '3458721',
        mcNumber: 'MC-672311',
        status: 'Active',
        city: 'Phoenix',
        state: 'AZ',
        country: 'US',
        drivers: 64,
        assets: 38,
        safetyRating: 'Conditional',
        createdAt: '2021-03-18',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-005',
        legalName: 'Great Lakes Carrier Group',
        dbaName: 'GLCG',
        dotNumber: '1120456',
        mcNumber: 'MC-445210',
        status: 'Active',
        city: 'Chicago',
        state: 'IL',
        country: 'US',
        drivers: 305,
        assets: 214,
        safetyRating: 'Satisfactory',
        createdAt: '2015-11-02',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-006',
        legalName: 'Evergreen Logistics Inc.',
        dbaName: 'Evergreen',
        dotNumber: '4482190',
        mcNumber: 'MC-998341',
        status: 'Pending',
        city: 'Seattle',
        state: 'WA',
        country: 'US',
        drivers: 22,
        assets: 12,
        safetyRating: 'Not Rated',
        createdAt: '2024-08-29',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-007',
        legalName: 'Maple Ridge Transport Co.',
        dbaName: 'Maple Ridge',
        dotNumber: '—',
        mcNumber: '—',
        status: 'Active',
        city: 'Calgary',
        state: 'AB',
        country: 'CA',
        drivers: 97,
        assets: 71,
        safetyRating: 'Satisfactory',
        createdAt: '2018-02-14',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-008',
        legalName: 'Lone Star Freightways LLC',
        dbaName: 'Lone Star',
        dotNumber: '3019887',
        mcNumber: 'MC-560712',
        status: 'Active',
        city: 'Dallas',
        state: 'TX',
        country: 'US',
        drivers: 178,
        assets: 122,
        safetyRating: 'Satisfactory',
        createdAt: '2016-05-30',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-009',
        legalName: 'Rocky Mountain Hauling Inc.',
        dbaName: 'Rocky Mtn Haul',
        dotNumber: '2774553',
        mcNumber: 'MC-311098',
        status: 'Inactive',
        city: 'Denver',
        state: 'CO',
        country: 'US',
        drivers: 0,
        assets: 4,
        safetyRating: 'Conditional',
        createdAt: '2019-07-11',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-010',
        legalName: 'Atlantic Coastal Transport LLC',
        dbaName: 'ACT',
        dotNumber: '1998732',
        mcNumber: 'MC-772104',
        status: 'Active',
        city: 'Jacksonville',
        state: 'FL',
        country: 'US',
        drivers: 134,
        assets: 89,
        safetyRating: 'Satisfactory',
        createdAt: '2018-10-05',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-011',
        legalName: 'Prairie Express Carriers',
        dbaName: 'Prairie Express',
        dotNumber: '—',
        mcNumber: '—',
        status: 'Active',
        city: 'Winnipeg',
        state: 'MB',
        country: 'CA',
        drivers: 41,
        assets: 27,
        safetyRating: 'Satisfactory',
        createdAt: '2022-01-20',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-012',
        legalName: 'Heartland Trucking Partners',
        dbaName: 'Heartland',
        dotNumber: '2554109',
        mcNumber: 'MC-489231',
        status: 'Suspended',
        city: 'Kansas City',
        state: 'MO',
        country: 'US',
        drivers: 58,
        assets: 44,
        safetyRating: 'Unsatisfactory',
        createdAt: '2017-03-08',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-013',
        legalName: 'Bay Area Logistics Inc.',
        dbaName: 'BAL',
        dotNumber: '3887221',
        mcNumber: 'MC-665442',
        status: 'Active',
        city: 'Oakland',
        state: 'CA',
        country: 'US',
        drivers: 201,
        assets: 145,
        safetyRating: 'Satisfactory',
        createdAt: '2014-12-01',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-014',
        legalName: 'Summit Peak Transport Corp.',
        dbaName: 'Summit Peak',
        dotNumber: '4221078',
        mcNumber: 'MC-803219',
        status: 'Active',
        city: 'Salt Lake City',
        state: 'UT',
        country: 'US',
        drivers: 73,
        assets: 52,
        safetyRating: 'Conditional',
        createdAt: '2020-09-17',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-015',
        legalName: 'St. Lawrence Cartage Ltd.',
        dbaName: 'St. Lawrence',
        dotNumber: '—',
        mcNumber: '—',
        status: 'Active',
        city: 'Montreal',
        state: 'QC',
        country: 'CA',
        drivers: 119,
        assets: 88,
        safetyRating: 'Satisfactory',
        createdAt: '2016-04-23',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-016',
        legalName: 'Blue Ridge Freight Services',
        dbaName: 'Blue Ridge',
        dotNumber: '1665328',
        mcNumber: 'MC-210098',
        status: 'Active',
        city: 'Charlotte',
        state: 'NC',
        country: 'US',
        drivers: 92,
        assets: 68,
        safetyRating: 'Satisfactory',
        createdAt: '2019-06-12',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-017',
        legalName: 'Desert Wind Transport LLC',
        dbaName: 'Desert Wind',
        dotNumber: '3101877',
        mcNumber: 'MC-554321',
        status: 'Active',
        city: 'Albuquerque',
        state: 'NM',
        country: 'US',
        drivers: 45,
        assets: 30,
        safetyRating: 'Conditional',
        createdAt: '2021-11-05',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-018',
        legalName: 'Pacific Crown Logistics Inc.',
        dbaName: 'Pacific Crown',
        dotNumber: '—',
        mcNumber: '—',
        status: 'Active',
        city: 'Vancouver',
        state: 'BC',
        country: 'CA',
        drivers: 156,
        assets: 102,
        safetyRating: 'Satisfactory',
        createdAt: '2015-07-28',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-019',
        legalName: 'Liberty Bell Carriers Corp.',
        dbaName: 'Liberty Bell',
        dotNumber: '2998012',
        mcNumber: 'MC-447781',
        status: 'Active',
        city: 'Philadelphia',
        state: 'PA',
        country: 'US',
        drivers: 110,
        assets: 77,
        safetyRating: 'Satisfactory',
        createdAt: '2017-08-19',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-020',
        legalName: 'Midwest Anchor Trucking',
        dbaName: 'Midwest Anchor',
        dotNumber: '2330917',
        mcNumber: 'MC-388102',
        status: 'Active',
        city: 'Indianapolis',
        state: 'IN',
        country: 'US',
        drivers: 88,
        assets: 61,
        safetyRating: 'Satisfactory',
        createdAt: '2018-11-30',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-021',
        legalName: 'Greenfield Transport Solutions',
        dbaName: 'Greenfield',
        dotNumber: '4487621',
        mcNumber: 'MC-901234',
        status: 'Pending',
        city: 'Columbus',
        state: 'OH',
        country: 'US',
        drivers: 12,
        assets: 8,
        safetyRating: 'Not Rated',
        createdAt: '2025-01-14',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-022',
        legalName: 'Silver Creek Hauling Inc.',
        dbaName: 'Silver Creek',
        dotNumber: '2110445',
        mcNumber: 'MC-675443',
        status: 'Active',
        city: 'Boise',
        state: 'ID',
        country: 'US',
        drivers: 36,
        assets: 24,
        safetyRating: 'Satisfactory',
        createdAt: '2020-04-09',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-023',
        legalName: 'Gateway Carriers LLC',
        dbaName: 'Gateway',
        dotNumber: '1899332',
        mcNumber: 'MC-220116',
        status: 'Active',
        city: 'St. Louis',
        state: 'MO',
        country: 'US',
        drivers: 127,
        assets: 94,
        safetyRating: 'Satisfactory',
        createdAt: '2016-09-14',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-024',
        legalName: 'Harborline Transport Co.',
        dbaName: 'Harborline',
        dotNumber: '3377004',
        mcNumber: 'MC-558820',
        status: 'Active',
        city: 'Boston',
        state: 'MA',
        country: 'US',
        drivers: 74,
        assets: 49,
        safetyRating: 'Conditional',
        createdAt: '2019-02-27',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-025',
        legalName: 'Thunder Bay Freight Ltd.',
        dbaName: 'Thunder Bay Freight',
        dotNumber: '—',
        mcNumber: '—',
        status: 'Inactive',
        city: 'Thunder Bay',
        state: 'ON',
        country: 'CA',
        drivers: 0,
        assets: 6,
        safetyRating: 'Not Rated',
        createdAt: '2018-05-21',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-026',
        legalName: 'Iron Horse Logistics LLC',
        dbaName: 'Iron Horse',
        dotNumber: '2668210',
        mcNumber: 'MC-338902',
        status: 'Active',
        city: 'Omaha',
        state: 'NE',
        country: 'US',
        drivers: 52,
        assets: 37,
        safetyRating: 'Satisfactory',
        createdAt: '2021-07-06',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-027',
        legalName: 'Coastal Edge Trucking Corp.',
        dbaName: 'Coastal Edge',
        dotNumber: '3229914',
        mcNumber: 'MC-771203',
        status: 'Active',
        city: 'Savannah',
        state: 'GA',
        country: 'US',
        drivers: 98,
        assets: 67,
        safetyRating: 'Satisfactory',
        createdAt: '2017-12-11',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-028',
        legalName: 'Crescent City Cartage',
        dbaName: 'Crescent City',
        dotNumber: '2881077',
        mcNumber: 'MC-491023',
        status: 'Active',
        city: 'New Orleans',
        state: 'LA',
        country: 'US',
        drivers: 61,
        assets: 42,
        safetyRating: 'Conditional',
        createdAt: '2019-10-08',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-029',
        legalName: 'Polar Star Transport Inc.',
        dbaName: 'Polar Star',
        dotNumber: '—',
        mcNumber: '—',
        status: 'Active',
        city: 'Edmonton',
        state: 'AB',
        country: 'CA',
        drivers: 143,
        assets: 96,
        safetyRating: 'Satisfactory',
        createdAt: '2016-01-17',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-030',
        legalName: 'Redwood Freight Partners',
        dbaName: 'Redwood',
        dotNumber: '3998021',
        mcNumber: 'MC-667719',
        status: 'Active',
        city: 'Sacramento',
        state: 'CA',
        country: 'US',
        drivers: 115,
        assets: 80,
        safetyRating: 'Satisfactory',
        createdAt: '2018-06-25',
        profilePath: '/account/profile',
    },
];

// ── Lookup helpers ────────────────────────────────────────────────────────────

export const getAccountById = (id: string): AccountRecord | undefined =>
    ACCOUNTS_DB.find(a => a.id === id);

export const uniqueValues = <K extends keyof AccountRecord>(key: K): Array<AccountRecord[K]> => {
    const seen = new Set<AccountRecord[K]>();
    const out: Array<AccountRecord[K]> = [];
    for (const a of ACCOUNTS_DB) {
        if (!seen.has(a[key])) {
            seen.add(a[key]);
            out.push(a[key]);
        }
    }
    return out;
};

// ── Column styling maps (shared by list and any future detail screens) ───────

export const STATUS_BADGE: Record<AccountStatus, string> = {
    Active: 'bg-emerald-100 text-emerald-700 border border-emerald-200',
    Inactive: 'bg-slate-100 text-slate-600 border border-slate-200',
    Suspended: 'bg-red-100 text-red-700 border border-red-200',
    Pending: 'bg-amber-100 text-amber-700 border border-amber-200',
};

export const RATING_BADGE: Record<SafetyRating, string> = {
    Satisfactory: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
    Conditional: 'bg-amber-50 text-amber-700 border border-amber-200',
    Unsatisfactory: 'bg-red-50 text-red-700 border border-red-200',
    'Not Rated': 'bg-slate-50 text-slate-500 border border-slate-200',
};
