// Accounts / Carriers — Frontend Mock Database
// Single source of truth for the Accounts list view and, eventually,
// per-carrier profile routing. Keep shape stable; pages import from here.

export type AccountStatus = 'Active' | 'Inactive' | 'Suspended' | 'Pending';
export type SafetyRating = 'Satisfactory' | 'Conditional' | 'Unsatisfactory' | 'Not Rated';
export type AccountCountry = 'US' | 'CA';

export interface AccountRecord {
    id: string;
    legalName: string;
    dbaName: string;
    dotNumber: string;
    cvorNumber: string;   // Ontario Commercial Vehicle Operator's Registration
    nscNumber: string;    // Canadian National Safety Code carrier #
    rinNumber: string;    // Registered Importer Number (cross-border)
    status: AccountStatus;
    city: string;
    state: string;
    country: AccountCountry;
    drivers: number;
    assets: number;
    safetyRating: SafetyRating;
    createdAt: string;
    profilePath: string;
}

export const ACCOUNTS_DB: AccountRecord[] = [
    {
        id: 'acct-001',
        legalName: 'Acme Trucking Inc.',
        dbaName: 'Acme Logistics',
        dotNumber: '1234567',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: 'RIN-0099',
        status: 'Active',
        city: 'Wilmington',
        state: 'DE',
        country: 'US',
        drivers: 22,
        assets: 18,
        safetyRating: 'Satisfactory',
        createdAt: '2019-01-15',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-002',
        legalName: 'Cascade Freight Systems LLC',
        dbaName: 'Cascade Freight',
        dotNumber: '2891034',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Portland',
        state: 'OR',
        country: 'US',
        drivers: 16,
        assets: 12,
        safetyRating: 'Satisfactory',
        createdAt: '2020-06-04',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-003',
        legalName: 'Northern Lights Transport Ltd.',
        dbaName: 'NL Transport',
        dotNumber: '',
        cvorNumber: 'CVOR-41289',
        nscNumber: 'ON-11234',
        rinNumber: '',
        status: 'Active',
        city: 'Mississauga',
        state: 'ON',
        country: 'CA',
        drivers: 24,
        assets: 20,
        safetyRating: 'Satisfactory',
        createdAt: '2017-09-22',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-004',
        legalName: 'Sunbelt Haulers Corporation',
        dbaName: 'Sunbelt Haulers',
        dotNumber: '3458721',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Phoenix',
        state: 'AZ',
        country: 'US',
        drivers: 14,
        assets: 10,
        safetyRating: 'Conditional',
        createdAt: '2021-03-18',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-005',
        legalName: 'Great Lakes Carrier Group',
        dbaName: 'GLCG',
        dotNumber: '1120456',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: 'RIN-2214',
        status: 'Active',
        city: 'Chicago',
        state: 'IL',
        country: 'US',
        drivers: 24,
        assets: 22,
        safetyRating: 'Satisfactory',
        createdAt: '2015-11-02',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-006',
        legalName: 'Evergreen Logistics Inc.',
        dbaName: 'Evergreen',
        dotNumber: '4482190',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Pending',
        city: 'Seattle',
        state: 'WA',
        country: 'US',
        drivers: 8,
        assets: 4,
        safetyRating: 'Not Rated',
        createdAt: '2024-08-29',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-007',
        legalName: 'Maple Ridge Transport Co.',
        dbaName: 'Maple Ridge',
        dotNumber: '',
        cvorNumber: '',
        nscNumber: 'AB-55410',
        rinNumber: '',
        status: 'Active',
        city: 'Calgary',
        state: 'AB',
        country: 'CA',
        drivers: 18,
        assets: 14,
        safetyRating: 'Satisfactory',
        createdAt: '2018-02-14',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-008',
        legalName: 'Lone Star Freightways LLC',
        dbaName: 'Lone Star',
        dotNumber: '3019887',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Dallas',
        state: 'TX',
        country: 'US',
        drivers: 22,
        assets: 17,
        safetyRating: 'Satisfactory',
        createdAt: '2016-05-30',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-009',
        legalName: 'Rocky Mountain Hauling Inc.',
        dbaName: 'Rocky Mtn Haul',
        dotNumber: '2774553',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Inactive',
        city: 'Denver',
        state: 'CO',
        country: 'US',
        drivers: 0,
        assets: 2,
        safetyRating: 'Conditional',
        createdAt: '2019-07-11',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-010',
        legalName: 'Atlantic Coastal Transport LLC',
        dbaName: 'ACT',
        dotNumber: '1998732',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: 'RIN-1873',
        status: 'Active',
        city: 'Jacksonville',
        state: 'FL',
        country: 'US',
        drivers: 20,
        assets: 16,
        safetyRating: 'Satisfactory',
        createdAt: '2018-10-05',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-011',
        legalName: 'Prairie Express Carriers',
        dbaName: 'Prairie Express',
        dotNumber: '',
        cvorNumber: '',
        nscNumber: 'MB-29011',
        rinNumber: '',
        status: 'Active',
        city: 'Winnipeg',
        state: 'MB',
        country: 'CA',
        drivers: 10,
        assets: 7,
        safetyRating: 'Satisfactory',
        createdAt: '2022-01-20',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-012',
        legalName: 'Heartland Trucking Partners',
        dbaName: 'Heartland',
        dotNumber: '2554109',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Suspended',
        city: 'Kansas City',
        state: 'MO',
        country: 'US',
        drivers: 12,
        assets: 9,
        safetyRating: 'Unsatisfactory',
        createdAt: '2017-03-08',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-013',
        legalName: 'Bay Area Logistics Inc.',
        dbaName: 'BAL',
        dotNumber: '3887221',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Oakland',
        state: 'CA',
        country: 'US',
        drivers: 23,
        assets: 19,
        safetyRating: 'Satisfactory',
        createdAt: '2014-12-01',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-014',
        legalName: 'Summit Peak Transport Corp.',
        dbaName: 'Summit Peak',
        dotNumber: '4221078',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Salt Lake City',
        state: 'UT',
        country: 'US',
        drivers: 14,
        assets: 11,
        safetyRating: 'Conditional',
        createdAt: '2020-09-17',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-015',
        legalName: 'St. Lawrence Cartage Ltd.',
        dbaName: 'St. Lawrence',
        dotNumber: '',
        cvorNumber: '',
        nscNumber: 'QC-77819',
        rinNumber: '',
        status: 'Active',
        city: 'Montreal',
        state: 'QC',
        country: 'CA',
        drivers: 19,
        assets: 15,
        safetyRating: 'Satisfactory',
        createdAt: '2016-04-23',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-016',
        legalName: 'Blue Ridge Freight Services',
        dbaName: 'Blue Ridge',
        dotNumber: '1665328',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Charlotte',
        state: 'NC',
        country: 'US',
        drivers: 17,
        assets: 13,
        safetyRating: 'Satisfactory',
        createdAt: '2019-06-12',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-017',
        legalName: 'Desert Wind Transport LLC',
        dbaName: 'Desert Wind',
        dotNumber: '3101877',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Albuquerque',
        state: 'NM',
        country: 'US',
        drivers: 11,
        assets: 8,
        safetyRating: 'Conditional',
        createdAt: '2021-11-05',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-018',
        legalName: 'Pacific Crown Logistics Inc.',
        dbaName: 'Pacific Crown',
        dotNumber: '',
        cvorNumber: '',
        nscNumber: 'BC-44210',
        rinNumber: '',
        status: 'Active',
        city: 'Vancouver',
        state: 'BC',
        country: 'CA',
        drivers: 21,
        assets: 17,
        safetyRating: 'Satisfactory',
        createdAt: '2015-07-28',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-019',
        legalName: 'Liberty Bell Carriers Corp.',
        dbaName: 'Liberty Bell',
        dotNumber: '2998012',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Philadelphia',
        state: 'PA',
        country: 'US',
        drivers: 19,
        assets: 14,
        safetyRating: 'Satisfactory',
        createdAt: '2017-08-19',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-020',
        legalName: 'Midwest Anchor Trucking',
        dbaName: 'Midwest Anchor',
        dotNumber: '2330917',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Indianapolis',
        state: 'IN',
        country: 'US',
        drivers: 15,
        assets: 12,
        safetyRating: 'Satisfactory',
        createdAt: '2018-11-30',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-021',
        legalName: 'Greenfield Transport Solutions',
        dbaName: 'Greenfield',
        dotNumber: '4487621',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Pending',
        city: 'Columbus',
        state: 'OH',
        country: 'US',
        drivers: 6,
        assets: 3,
        safetyRating: 'Not Rated',
        createdAt: '2025-01-14',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-022',
        legalName: 'Silver Creek Hauling Inc.',
        dbaName: 'Silver Creek',
        dotNumber: '2110445',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Boise',
        state: 'ID',
        country: 'US',
        drivers: 9,
        assets: 6,
        safetyRating: 'Satisfactory',
        createdAt: '2020-04-09',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-023',
        legalName: 'Gateway Carriers LLC',
        dbaName: 'Gateway',
        dotNumber: '1899332',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'St. Louis',
        state: 'MO',
        country: 'US',
        drivers: 20,
        assets: 15,
        safetyRating: 'Satisfactory',
        createdAt: '2016-09-14',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-024',
        legalName: 'Harborline Transport Co.',
        dbaName: 'Harborline',
        dotNumber: '3377004',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Boston',
        state: 'MA',
        country: 'US',
        drivers: 15,
        assets: 11,
        safetyRating: 'Conditional',
        createdAt: '2019-02-27',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-025',
        legalName: 'Thunder Bay Freight Ltd.',
        dbaName: 'Thunder Bay Freight',
        dotNumber: '',
        cvorNumber: 'CVOR-33087',
        nscNumber: 'ON-33087',
        rinNumber: '',
        status: 'Inactive',
        city: 'Thunder Bay',
        state: 'ON',
        country: 'CA',
        drivers: 0,
        assets: 3,
        safetyRating: 'Not Rated',
        createdAt: '2018-05-21',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-026',
        legalName: 'Iron Horse Logistics LLC',
        dbaName: 'Iron Horse',
        dotNumber: '2668210',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Omaha',
        state: 'NE',
        country: 'US',
        drivers: 13,
        assets: 9,
        safetyRating: 'Satisfactory',
        createdAt: '2021-07-06',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-027',
        legalName: 'Coastal Edge Trucking Corp.',
        dbaName: 'Coastal Edge',
        dotNumber: '3229914',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Savannah',
        state: 'GA',
        country: 'US',
        drivers: 18,
        assets: 13,
        safetyRating: 'Satisfactory',
        createdAt: '2017-12-11',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-028',
        legalName: 'Crescent City Cartage',
        dbaName: 'Crescent City',
        dotNumber: '2881077',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'New Orleans',
        state: 'LA',
        country: 'US',
        drivers: 13,
        assets: 10,
        safetyRating: 'Conditional',
        createdAt: '2019-10-08',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-029',
        legalName: 'Polar Star Transport Inc.',
        dbaName: 'Polar Star',
        dotNumber: '',
        cvorNumber: '',
        nscNumber: 'AB-66190',
        rinNumber: '',
        status: 'Active',
        city: 'Edmonton',
        state: 'AB',
        country: 'CA',
        drivers: 21,
        assets: 16,
        safetyRating: 'Satisfactory',
        createdAt: '2016-01-17',
        profilePath: '/account/profile',
    },
    {
        id: 'acct-030',
        legalName: 'Redwood Freight Partners',
        dbaName: 'Redwood',
        dotNumber: '3998021',
        cvorNumber: '',
        nscNumber: '',
        rinNumber: '',
        status: 'Active',
        city: 'Sacramento',
        state: 'CA',
        country: 'US',
        drivers: 19,
        assets: 13,
        safetyRating: 'Satisfactory',
        createdAt: '2018-06-25',
        profilePath: '/account/profile',
    },
];

// ── Lookup helpers ────────────────────────────────────────────────────────────

export const getAccountById = (id: string): AccountRecord | undefined =>
    ACCOUNTS_DB.find(a => a.id === id);

// Insert a new carrier at the top of the list. Mutates the module-level
// ACCOUNTS_DB so subsequent reads reflect the addition.
export const addAccountRecord = (record: AccountRecord): void => {
    ACCOUNTS_DB.unshift(record);
};

export const uniqueValues = <K extends keyof AccountRecord>(key: K): Array<AccountRecord[K]> => {
    const seen = new Set<AccountRecord[K]>();
    const out: Array<AccountRecord[K]> = [];
    for (const a of ACCOUNTS_DB) {
        if (!seen.has(a[key])) {
            seen.add(a[key]);
            out.push(a[key]);
        }
    }
    return out;
};

// Concatenate the Canadian / cross-border IDs for display + search.
// Returns the first non-empty of CVOR, NSC, RIN (joined with " / " if multiple).
export const cvorNscRinDisplay = (a: AccountRecord): string => {
    const parts = [a.cvorNumber, a.nscNumber, a.rinNumber].filter(p => p && p.trim().length > 0);
    return parts.length > 0 ? parts.join(' / ') : '';
};

// ── Column styling maps (shared by list and any future detail screens) ───────

export const STATUS_BADGE: Record<AccountStatus, string> = {
    Active: 'bg-emerald-100 text-emerald-700 border border-emerald-200',
    Inactive: 'bg-slate-100 text-slate-600 border border-slate-200',
    Suspended: 'bg-red-100 text-red-700 border border-red-200',
    Pending: 'bg-amber-100 text-amber-700 border border-amber-200',
};

export const RATING_BADGE: Record<SafetyRating, string> = {
    Satisfactory: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
    Conditional: 'bg-amber-50 text-amber-700 border border-amber-200',
    Unsatisfactory: 'bg-red-50 text-red-700 border border-red-200',
    'Not Rated': 'bg-slate-50 text-slate-500 border border-slate-200',
};
